global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "heart-disease-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - heart-disease-api-service:8000
